pharmacy_landing:
    resource: "@PharmacyLandingBundle/Controller/"
    type:     annotation
    prefix:   /

pharmacy_api:
    resource: "@PharmacyApiBundle/Resources/config/routing.yml"
    prefix:   /api

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc